config/routes.rb
Rails.application.routes.draw do
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
  resources :o2s
  resources :enames
  resources :evaluacions
  resources :anuncios
  resources :horarios
  resources :consultations
  resources :noticia
  resources :jugadors
  resources :entrenadors
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get '/evaluaciones', to: 'evaluacions#main_index'
  get '/busqueda', to: "jugadors#search"
end

app/models/anuncio.rb
class Anuncio < ApplicationRecord
end

app/models/consultation.rb
class Consultation < ApplicationRecord
    validates_presence_of :start_time, :title, :description
end

app/models/ename.rb
class Ename < ApplicationRecord
    has_many :evaluacions, dependent: :destroy
    has_many :evaluacion_tecs, dependent: :destroy
end

app/models/entrenador.rb
class Entrenador < ApplicationRecord
    has_one_attached :avatar
end

app/models/evaluacion.rb
class Evaluacion < ApplicationRecord
    before_save :set_defaults
    belongs_to :ename , optional: true
    belongs_to :jugador
    validates_presence_of :ename_id
    
    private
    def set_defaults
        self.altura ||= 0
        self.embergadura ||= 0
        self.peso ||= 0
        self.max_pres ||= 0
        self.max_squat ||= 0
        self.max_dl ||= 0
        self.max_jump_incompleto ||= 0
        self.max_jump_completo ||= 0
        self.max_jump_libre ||= 0
        self.max_jump_carrera ||= 0
        self.max_v1 ||= 0
        self.max_v2 ||= 0
        self.max_time ||= "00:00"
    end

end

app/models/evaluacion_tec.rb
class EvaluacionTec < ApplicationRecord
    belongs_to :jugador
end

app/models/horario.rb
class Horario < ApplicationRecord
end

app/models/jugador.rb
class Jugador < ApplicationRecord
    has_one_attached :avatar
    has_many :evaluacions, dependent: :destroy
    has_many :evaluacion_tecs, dependent: :destroy
    validates_presence_of :fecha, :name, :last_name1, :rut, :categoria
end

app/models/noticium.rb
class Noticium < ApplicationRecord
    has_many_attached : photos
end

app/models/o2.rb
class O2 < ApplicationRecord
    validates_presence_of :fecha ,:title, :categoria, :torneo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar

  #this gives you custom message for the error
  validates :email, :uniqueness => { :message => "El correo ya esta registrado." }
  
  #an even better way
  def email=(email)
    super(email.downcase.strip)
  end
end

app/controllers/enames_controller.rb
class EnamesController < ApplicationController
  before_action :set_ename, only: %i[ show edit update destroy ]

  # GET /enames or /enames.json
  def index
    @enames = Ename.all
  end

  # GET /enames/1 or /enames/1.json
  def show
  end

  # GET /enames/new
  def new
    @ename = Ename.new
  end

  # GET /enames/1/edit
  def edit
  end

  # POST /enames or /enames.json
  def create
    @ename = Ename.new(ename_params)

    respond_to do |format|
      if @ename.save
        format.html { redirect_to enames_path, notice: "Ename was successfully created." }
        format.json { render :show, status: :created, location: @ename }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ename.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enames/1 or /enames/1.json
  def update
    respond_to do |format|
      if @ename.update(ename_params)
        format.html { redirect_to enames_path, notice: "Ename was successfully updated." }
        format.json { render :show, status: :ok, location: @ename }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ename.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enames/1 or /enames/1.json
  def destroy
    @ename.destroy

    respond_to do |format|
      format.html { redirect_to enames_url, notice: "Ename was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ename
      @ename = Ename.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ename_params
      params.fetch(:ename, {}).permit(:title)
    end
end

app/helpers/anuncios_helper.rb
module AnunciosHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/enames_helper.rb
module EnamesHelper
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/noticia_helper.rb
module NoticiaHelper
end

app/helpers/o2s_helper.rb
module O2sHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/enames/_ename.html.erb
<div id="<%= dom_id ename %>">
</div>

app/views/enames/_form.html.erb
<style>
  #conteiner_3{
    margin-left: 0px;
    margin-right: 0px;
    margin-top: 3%;
    margin-bottom: 2%;
    width : auto;
  }
  #form1{
    width : 100% ;
  }
  #formspace{
    margin-left: 10%;
    margin-right: 10%;
  }
  #datos{
    margin-bottom: 2%;
  }
  select{
    width: 100%;
    padding: 6px 12px;
    border: none;
    border-radius: 4px;
    background-color: #fff; 
  }
  #botones{
    margin-top: 2%;
  }

</style>

<div class="row ml-0" id="conteiner_3">
  <div class="col" id=formspace>
    <%= form_with model: ename, local: true do |form| %>
      <%= errors_for ename %>
      <h2 id="datos">Datos de la Evaluación </h2>
      <div class="row g-3">
        <div class="col-md-12">
          <div class="mb-3" id="form1">
            <%= form.label 'Nombre de la Evaluación', class: "form-label" %>
            <%= form.text_field :title, class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="form-group mt-2 text-center" id="botones"
      >
        <%= form.submit 'Guardar Nombre de Evaluación', class: 'btn btn-primary' %>
        <%= link_to "Volver", :back, class: ["btn", "btn-secondary"] %>
      </div>
    <% end %>
  </div>
</div>

app/views/enames/edit.html.erb
<h1>Editing ename</h1>

<%= render "form", ename: @ename %>

<br>

<div>
  <%= link_to "Show this ename", @ename %> |
  <%= link_to "Back to enames", enames_path %>
</div>

app/views/enames/index.html.erb
<style>
  h1{
    margin-top: 2%;
    margin-left: 8%;
  }
  h5{
    margin-top: 1%;
    margin-left: 8%;
  }

  #newboton{
    margin-left: 2rem ;
    width : 10em;
  }
  #conteiner_row{
    margin-left: 10%;
    margin-right: 0px;
    margin-top: 2%;
    margin-bottom: 2%;
  }
  #lista{
    width : auto;
    margin-left: 10%;
    margin-right: 10%;
    background-color: #d4d3d4;
    background-opacity: 0.8;
  }
  #butoncito{
    margin-top: 0;
    margin-bottom: 3%;
    width: 60%;
    align: center;
  }
  #tablaa{
    color: #212529;
  }
  #tablaa:hover{
    text-decoration: underline;
  }
  #tj{
    width:100%;
    border: 1px solid;
    border-color: grey;
    border-collapse:collapse;
    border-radius:6px;
    box-shadow: 0 0 0 1px #666;
    background-color: #fff;
  }
  #lel{
    text-align: center;
    width: 60%;
    background-color: red;
  }
  #lel:hover,#lel2:hover{
    text-decoration: none;
    color: white;
    opacity: 0.8;
  }
  #lel2{
    text-align: center;
    width: 60%;
    background-color: green;

  }
  #botons{
    width: 60%;
    text-align: center;
    margin-left:20%;
    margin-right:20%;
    margin-top:2%;

  }
</style>
<div id="jugadores">
  <title>Evaluaciones | Data</title>
  <h1>Periodos de Evaluación</h1>
  <div class="row" id="botons">
    <div class="col">
    <%= link_to "Nuevo Periodo", new_ename_path, class: ["btn", "btn-primary"], id:"butoncito" %>
    </div>
    <div class="col">
    <%= link_to 'Volver a Evaluaciones', evaluaciones_path , class: ["btn", "btn-primary"], id:"butoncito"%>
    </div>
  </div>
  <div class="card-header pb-0" id="lista">
    <div class="card-body">
      <table class="table table-striped" style="width:100%" id="tj">
        <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Nombre</th>
          <th scope="col">Fecha</th>
          <th scope="col" colspan="1"> </th>
        </tr>
        </thead>
        <tbody>
        <% @enames.reverse_each do |ename| %> 
          <tr>
            <td style="vertical-align: middle;"># <%= ename.id %></td>
            <td style="vertical-align: middle;"><%= ename.title %></td>
            <td style="vertical-align: middle;"><%= ename.created_at.strftime('%d-%m-%G') %></td>
            <td style="vertical-align: middle;"><%= link_to "Delete", ename_path(ename), data: { turbo_method: "delete", turbo_confirm: "Borrar el periodo borrará todas las evaluaciones asociadas al mismo." }, class: ['btn', 'btn-danger']  %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/enames/new.html.erb
<h1>New ename</h1>

<%= render "form", ename: @ename %>

<br>

<div>
  <%= link_to "Back to enames", enames_path %>
</div>

app/views/enames/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ename %>

<div>
  <%= link_to "Edit this ename", edit_ename_path(@ename) %> |
  <%= link_to "Back to enames", enames_path %>

  <%= button_to "Destroy this ename", @ename, method: :delete %>
</div>