config/routes.rb
Rails.application.routes.draw do
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
  resources :o2s
  resources :enames
  resources :evaluacions
  resources :anuncios
  resources :horarios
  resources :consultations
  resources :noticia
  resources :jugadors
  resources :entrenadors
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get '/evaluaciones', to: 'evaluacions#main_index'
  get '/busqueda', to: "jugadors#search"
end

app/models/anuncio.rb
class Anuncio < ApplicationRecord
end

app/models/consultation.rb
class Consultation < ApplicationRecord
    validates_presence_of :start_time, :title, :description
end

app/models/ename.rb
class Ename < ApplicationRecord
    has_many :evaluacions, dependent: :destroy
    has_many :evaluacion_tecs, dependent: :destroy
end

app/models/entrenador.rb
class Entrenador < ApplicationRecord
    has_one_attached :avatar
end

app/models/evaluacion.rb
class Evaluacion < ApplicationRecord
    before_save :set_defaults
    belongs_to :ename , optional: true
    belongs_to :jugador
    validates_presence_of :ename_id
    
    private
    def set_defaults
        self.altura ||= 0
        self.embergadura ||= 0
        self.peso ||= 0
        self.max_pres ||= 0
        self.max_squat ||= 0
        self.max_dl ||= 0
        self.max_jump_incompleto ||= 0
        self.max_jump_completo ||= 0
        self.max_jump_libre ||= 0
        self.max_jump_carrera ||= 0
        self.max_v1 ||= 0
        self.max_v2 ||= 0
        self.max_time ||= "00:00"
    end

end

app/models/evaluacion_tec.rb
class EvaluacionTec < ApplicationRecord
    belongs_to :jugador
end

app/models/horario.rb
class Horario < ApplicationRecord
end

app/models/jugador.rb
class Jugador < ApplicationRecord
    has_one_attached :avatar
    has_many :evaluacions, dependent: :destroy
    has_many :evaluacion_tecs, dependent: :destroy
    validates_presence_of :fecha, :name, :last_name1, :rut, :categoria
end

app/models/noticium.rb
class Noticium < ApplicationRecord
    has_many_attached : photos
end

app/models/o2.rb
class O2 < ApplicationRecord
    validates_presence_of :fecha ,:title, :categoria, :torneo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar

  #this gives you custom message for the error
  validates :email, :uniqueness => { :message => "El correo ya esta registrado." }
  
  #an even better way
  def email=(email)
    super(email.downcase.strip)
  end
end

app/controllers/entrenadors_controller.rb
class EntrenadorsController < ApplicationController
  before_action :set_entrenador, only: %i[ show edit update destroy ]

  # GET /entrenadors or /entrenadors.json
  def index
    @entrenadors = Entrenador.all
  end

  # GET /entrenadors/1 or /entrenadors/1.json
  def show
  end

  # GET /entrenadors/new
  def new
    @entrenador = Entrenador.new
  end

  # GET /entrenadors/1/edit
  def edit
  end

  # POST /entrenadors or /entrenadors.json
  def create
    params[:entrenador][:fullname] = params[:entrenador][:name] +" "+params[:entrenador][:last_name]
    @entrenador = Entrenador.new(entrenador_params)
    respond_to do |format|
      if @entrenador.save
        format.html { redirect_to entrenador_url(@entrenador), notice: "Entrenador was successfully created." }
        format.json { render :show, status: :created, location: @entrenador }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entrenador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entrenadors/1 or /entrenadors/1.json
  def update
    respond_to do |format|
      params[:entrenador][:fullname] = params[:entrenador][:name] +" "+params[:entrenador][:last_name]
      if @entrenador.update(entrenador_params)
        format.html { redirect_to entrenador_url(@entrenador), notice: "Entrenador was successfully updated." }
        format.json { render :show, status: :ok, location: @entrenador }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entrenador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entrenadors/1 or /entrenadors/1.json
  def destroy
    @entrenador.destroy

    respond_to do |format|
      format.html { redirect_to entrenadors_url, notice: "Entrenador was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrenador
      @entrenador = Entrenador.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entrenador_params
      params.fetch(:entrenador, {}).permit(:id, :name, :last_name, :mail, :telephone, :fullname,  :rol, :avatar)
    end
end

app/helpers/anuncios_helper.rb
module AnunciosHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/enames_helper.rb
module EnamesHelper
end

app/helpers/entrenadors_helper.rb
module EntrenadorsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/noticia_helper.rb
module NoticiaHelper
end

app/helpers/o2s_helper.rb
module O2sHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entrenadors/_entrenador.html.erb
<div id="<%= dom_id entrenador %>">
</div>

app/views/entrenadors/_form.html.erb
<style>
  #conteiner_3{
    margin-left: 0px;
    margin-right: 0px;
    margin-top: 3%;
    margin-bottom: 2%;
    width : auto;
  }
  #form1{
    width : 100% ;
  }
  #formspace{
    margin-left: 10%;
    margin-right: 10%;
  }
  #datos{
    margin-bottom: 2%;
  }
  select{
    width: 100%;
    padding: 6px 12px;
    border: none;
    border-radius: 4px;
    background-color: #fff; 
  }
  #botones{
    margin-top: 2%;
  }

</style>
<div class="row ml-0" id="conteiner_3">
  <div class="col" id=formspace>
    <%= form_with model: entrenador, local: true do |form| %>
      <%= errors_for entrenador %>
      <div class="mb-3" id="form1">
        <%= form.label 'Foto' %>
        <%= form.file_field :avatar, class: "form-control-file" %>
      </div> 
      <div class="row g-3">
        <div class="col-md-6">
          <div class="mb-3" id="form1">
            <%= form.label 'Nombre', class: "form-label" %>
            <%= form.text_field :name, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="mb-3" id="form1">
            <%= form.label 'Apellidos', class: "form-label" %>
            <%= form.text_field :last_name, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="mb-3" id="form1">
          <%= form.label "Correo *", class: "form-label" %>
          <%= form.text_field :mail, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="mb-3" id="form1">
            <%= form.label "Teléfono *", class: "form-label" %>
            <%= form.text_field :telephone, class: "form-control", placeholder:"+569..." %>
          </div>
        </div>
        <div class="col-6">
          <div class="mb-3" id="form1">
            <%= form.label "Puesto", class: "form-label" %>
            <%= form.select :rol, ["Entrenador","Preparador Físico", "Kinesiólogo", "Piscólogo", "Ayudante", "Practicante", "Jefe de Entrenadores", "Jefe de Rama", "Presidente de Rama", "Secretario", "Tesorero", "Fotografo"], class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="form-group mt-2 text-center" id="botones">
        <%= form.submit 'Guardar Jugador', class: 'btn btn-primary' %>
        <%= link_to "Volver", :back, class: ["btn", "btn-secondary"] %>
      </div>
    <% end %>
  </div>
</div>

app/views/entrenadors/edit.html.erb
<h1>Editing entrenador</h1>

<%= render "form", entrenador: @entrenador %>

<br>

<div>
  <%= link_to "Show this entrenador", @entrenador %> |
  <%= link_to "Back to entrenadors", entrenadors_path %>
</div>

app/views/entrenadors/index.html.erb
<p style="color: green"><%= notice %></p>
<title>Cuerpo Técnico</title>
<div id="jugadores">
  <h1 id="titulo1">Cuerpo Técnico</h1>
  <div class="row justify-content-center" id="conteiner_row">
    <div class="col-md-auto">
    <a class="btn btn-primary" id="newboton" href= <%= new_entrenador_path %> role="button">Añadir Entrenador</a>
    </div>

  </div>

<div id="entrenadors">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css" integrity="sha256-3sPp8BkKUE7QyPSl6VfBByBroQbKxKG7tsusY2mhbVY=" crossorigin="anonymous" />
  <div class="container">
    <div class="row justify-content-center">
      <% @entrenadors.each do |entrenador| %>
        <div class="col-md-6 col-lg-4 mb-30">
          <div class="team-item">
            <div class="mb-30 position-relative d-flex align-items-center" id="tarjeta1">
              <span class="socials d-inline-block">
                  <a href="#" class="zmdi zmdi-facebook"></a>
                  <a href="#" class="zmdi zmdi-twitter"></a>
                  <a href="#" class="zmdi zmdi-google"></a>
                  <a href="#" class="zmdi zmdi-instagram"></a>
              </span>
              <span class="img-holder d-inline-block">
                <a href= <%= entrenador_url(entrenador)%>> <%= image_tag(entrenador.avatar.attached? ? entrenador.avatar : "profile.png", id:"avatares") %></a>
              </span>
            </div>
            <div class="team-content">
              <h5 class="mb-2" id="tarjeta2"><%=entrenador.name + " " + entrenador.last_name%></h5>
              <p class="text-uppercase mb-0"><%= entrenador.rol %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>


<style>
  .team-item {
    padding: 35px;
    padding-right: 0;
    position: relative;
    z-index: 0;
  }
  
  .team-item:after, .team-item:before {
    content: "";
    position: absolute;
    -webkit-box-shadow: 0 5px 30px 0 rgba(39, 39, 39, 0.15);
            box-shadow: 0 5px 30px 0 rgba(39, 39, 39, 0.15);
    border-radius: 10px;
    z-index: -1;
  }
  
  .team-item:before {
    height: 100%;
    background-color: #fff;
    left: 0;
    top: 0;
    right: 30px;
    -webkit-transition: all 0.3s ease;
    transition: all 0.3s ease;
  }
  
  .team-item:after {
    height: 6px;
    width: calc(100% - 30px);
    background-color: #0D6EFD;
    left: 0;
    bottom: 0;
    -webkit-transition: all 0.3s linear;
    transition: all 0.3s linear;
  }
  
  .team-item:hover:after {
    height: 100%;
  }
  
  .team-item .img-holder {
    -ms-flex-negative: 0;
        flex-shrink: 0;
    -webkit-box-shadow: 0 0 20px 0 rgba(51, 51, 51, 0.2);
            box-shadow: 0 0 20px 0 rgba(51, 51, 51, 0.2);
    border-radius: 10px;
    width: calc(100% - 70px);
    margin-left: 70px;
    overflow: hidden;
  }
  
  .team-item .img-holder img {
    border-radius: 10px;
    width: 100%;
    -webkit-transform: scale(1.1);
            transform: scale(1.1);
    -webkit-transition: all 0.6s ease;
    transition: all 0.6s ease;
  }
  
  .team-item:hover .img-holder img {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
  
  .team-item .socials {
    position: absolute;
  }
  
  .team-item .socials a {
    display: block;
    margin-right: 0;
    margin-bottom: 15px;
    -webkit-box-shadow: 0 3px 2px 0 rgba(0, 0, 0, 0.12);
            box-shadow: 0 3px 2px 0 rgba(0, 0, 0, 0.12);
  }
  
  .team-item .socials a:last-of-type {
    margin-bottom: 0;
  }
  
  .team-item .team-content {
    margin-right: 70px;
    text-align: center;
  }
  
  .team-item .team-content h5 {
    color: #101f41;
    -webkit-transition: all 0.4s ease;
    transition: all 0.4s ease;
  }
  
  .team-item .team-content p {
    color: #4e63d7;
    -webkit-transition: all 0.4s ease;
    transition: all 0.4s ease;
    font-weight: 600;
    font-size: 14px;
  }
  
  .team-item:hover .team-content h5, .team-item:hover .team-content p {
    color: #fff;
    -webkit-transition: all 0.3s ease;
    transition: all 0.3s ease;
  }
  
  .d-inline-block {
      display: inline-block!important;
  }
  
  .socials a {
      width: 35px;
      height: 35px;
      background-color: #6893e1;
      border-radius: 50%;
      -webkit-box-shadow: 0 3px 2px 0 #516cd9;
      box-shadow: 0 3px 2px 0 #516cd9;
      text-align: center;
      color: #fff;
      padding-top: 10px;
      font-size: 16px;
      margin-right: 10px;
      -webkit-transition: all 0.3s ease;
      transition: all 0.3s ease;
  }
  
 .my-2 {
      margin-bottom: .5rem!important;
  }
  #tarjeta2{
    margin-bottom: .5rem!important;
  }
  #tarjeta2:hover{
    color: white;
  }

  h5 {
      font-size: 21px;
  }
  
  #tarjeta1{
      margin-bottom: 30px;
  }
  #conteiner_row{
    margin-right: 0px;
    margin-top: 2%;
    margin-bottom: 2%;
  }
  #titulo1{
      margin-top: 2%;
      text-align: center;
    }
  .container{
    margin-bottom: 4%;
  }
</style>
    

app/views/entrenadors/new.html.erb
<h1>New entrenador</h1>

<%= render "form", entrenador: @entrenador %>

<br>

<div>
  <%= link_to "Back to entrenadors", entrenadors_path %>
</div>

app/views/entrenadors/show.html.erb
<title><%=@entrenador.name[0]+". "+@entrenador.last_name + " | "+ @entrenador.rol%></title>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

<section id="about-section" class="pt-5 pb-5">
    <div class="container wrapabout">
        <div class="red"></div>
        <div class="row" id="centerr">
            <div class="col-lg-6 align-items-center justify-content-left d-flex mb-5 mb-lg-0">
                <div class="blockabout" id="xdd">
                    <div class="blockabout-inner text-center text-sm-start"id="xdd">
                        <div class="title-big pb-3 mb-3">
                            <h3><%=@entrenador.name%> <%=@entrenador.last_name%></h3>
                            <h4 class="description-p text-muted pe-0 pe-lg-0">
                            <%= @entrenador.rol%>
                        </h4>
                        </div>
                        <p class="description-p text-muted pe-0 pe-lg-0">Lorem ipsum dolor sit amet consectetur \n adipisicing elit. Natus quas optio reiciendis deleniti voluptatem facere.</p>
                        <p class="description-p text-muted pe-0 pe-lg-0">Lorem ipsum dolor sit amet consectetur \n adipisicing elit. Natus quas optio reiciendis deleniti voluptatem facere.</p>
                        <p class="description-p text-muted pe-0 pe-lg-0">Lorem ipsum dolor sit amet consectetur \n adipisicing elit. Natus quas optio reiciendis deleniti voluptatem facere.</p>
                        <p class="description-p text-muted pe-0 pe-lg-0">Lorem ipsum dolor sit amet consectetur \n adipisicing elit. Natus quas optio reiciendis deleniti voluptatem facere.</p>
                        <p class="description-p text-muted pe-0 pe-lg-0">Lorem ipsum dolor sit amet consectetur \n adipisicing elit. Natus quas optio reiciendis deleniti voluptatem facere.</p>
                        <p class="description-p text-muted pe-0 pe-lg-0">Lorem ipsum dolor sit amet consectetur \n adipisicing elit. Natus quas optio reiciendis deleniti voluptatem facere.</p>
                        
                        
                        <div class="sosmed-horizontal pt-3 pb-3">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mt-5 mt-lg-0">
                <figure class="potoaboutwrap">
                    <%= image_tag(@entrenador.avatar.attached? ? @entrenador.avatar : "profile.png", id:"avatares") %>
                </figure>
            </div>
        </div>
    </div>
</section>
<div class="container mt-5 text-center">
  <div>
    <%= link_to "Editar Datos", edit_entrenador_path(@entrenador) , class: ["btn", "btn-primary"] %> 
    <%= link_to "Volver a Entrenadores", entrenadors_path , class: ["btn", "btn-secondary"] %>
    <%= button_to "Eliminar Entrenador", @entrenador, method: :delete , class: 'btn btn-danger', id:'botone' %>
  </div>
</div>
<style>
  #botone{
    margin-top: 1%;
  }
  #centerr{
    margin-left: 10%;
  }
  #avatares{
    width: 60%;
    height: auto;
    border-radius: 25px;
  }
  #xdd{
    border-radius: 25px;
  }
  #about-section {
    position: relative;
  }

  .blockabout {
      padding: 20px;
      background: white;
  }

  .blockabout-inner {
      padding: 30px;
      border: 1px solid rgba(32, 33, 36, 0.1);
  }

  .sosmed-horizontal a i {
      border: 1px solid #070707;
      border-radius: 50%;
      color: #070707;
      display: inline-block;
      height: 30px;
      width: 30px;
      line-height: 30px;
      margin: auto 3px;
      font-size: 15px;
      text-align: center;
      transition: all 0.3s;
  }

  .rey-btn {
      border: 2px solid #070707;
      padding: 10px 40px;
      text-transform: uppercase;
      letter-spacing: 2px;
      font-size: 13px;
      font-weight: 700;
      border-radius: 50px;
      transition: all 0.3s;
  }
</style>