config/routes.rb
Rails.application.routes.draw do
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
  resources :o2s
  resources :enames
  resources :evaluacions
  resources :anuncios
  resources :horarios
  resources :consultations
  resources :noticia
  resources :jugadors
  resources :entrenadors
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get '/evaluaciones', to: 'evaluacions#main_index'
  get '/busqueda', to: "jugadors#search"
end

app/models/anuncio.rb
class Anuncio < ApplicationRecord
end

app/models/consultation.rb
class Consultation < ApplicationRecord
    validates_presence_of :start_time, :title, :description
end

app/models/ename.rb
class Ename < ApplicationRecord
    has_many :evaluacions, dependent: :destroy
    has_many :evaluacion_tecs, dependent: :destroy
end

app/models/entrenador.rb
class Entrenador < ApplicationRecord
    has_one_attached :avatar
end

app/models/evaluacion.rb
class Evaluacion < ApplicationRecord
    before_save :set_defaults
    belongs_to :ename , optional: true
    belongs_to :jugador
    validates_presence_of :ename_id
    
    private
    def set_defaults
        self.altura ||= 0
        self.embergadura ||= 0
        self.peso ||= 0
        self.max_pres ||= 0
        self.max_squat ||= 0
        self.max_dl ||= 0
        self.max_jump_incompleto ||= 0
        self.max_jump_completo ||= 0
        self.max_jump_libre ||= 0
        self.max_jump_carrera ||= 0
        self.max_v1 ||= 0
        self.max_v2 ||= 0
        self.max_time ||= "00:00"
    end

end

app/models/evaluacion_tec.rb
class EvaluacionTec < ApplicationRecord
    belongs_to :jugador
end

app/models/horario.rb
class Horario < ApplicationRecord
end

app/models/jugador.rb
class Jugador < ApplicationRecord
    has_one_attached :avatar
    has_many :evaluacions, dependent: :destroy
    has_many :evaluacion_tecs, dependent: :destroy
    validates_presence_of :fecha, :name, :last_name1, :rut, :categoria
end

app/models/noticium.rb
class Noticium < ApplicationRecord
    has_many_attached : photos
end

app/models/o2.rb
class O2 < ApplicationRecord
    validates_presence_of :fecha ,:title, :categoria, :torneo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar

  #this gives you custom message for the error
  validates :email, :uniqueness => { :message => "El correo ya esta registrado." }
  
  #an even better way
  def email=(email)
    super(email.downcase.strip)
  end
end

app/controllers/jugadors_controller.rb
class JugadorsController < ApplicationController
  before_action :set_jugador, only: %i[ show edit update destroy ]

  # GET /jugadors or /jugadors.json
  def index
    if params[:view].present?
      @pagy, @jugadors = pagy(Jugador.where(categoria: params[:view]))
    else
      @pagy, @jugadors = pagy(Jugador.all)
      render 'index'
    end
  end

  # GET /jugadors/1 or /jugadors/1.json
  def show
  end

  # GET /jugadors/new
  def new
    @jugador = Jugador.new
  end

  # GET /jugadors/1/edit
  def edit
  end

  def search
    if  params[:search].blank?
      redirect_to jugadors_path and return
    else
      @parameter = params[:search].downcase
      @jugadors = Jugador.where("lower(name) LIKE ? or lower(last_name1) LIKE ? or lower(categoria) LIKE ? or lower(posicion) LIKE ?",
        "%#{@parameter}%",
        "%#{@parameter}%",
        "%#{@parameter}%",
        "%#{@parameter}%")
    end
  end

  # POST /jugadors or /jugadors.json
  def create
    params[:jugador][:fullname] = params[:jugador][:name] +" "+params[:jugador][:name2] +" "+params[:jugador][:last_name1] +" "+params[:jugador][:last_name2]
    @jugador = Jugador.new(jugador_params)

    respond_to do |format|
      if @jugador.save
        
        format.html { redirect_to jugador_url(@jugador), notice: "Jugador was successfully created." }
        format.json { render :show, status: :created, location: @jugador }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @jugador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jugadors/1 or /jugadors/1.json
  def update
    respond_to do |format|
      params[:jugador][:fullname] = params[:jugador][:name] +" "+params[:jugador][:name2] +" "+params[:jugador][:last_name1] +" "+params[:jugador][:last_name2]
      if @jugador.update(jugador_params)
        format.html { redirect_to jugador_url(@jugador), notice: "Jugador was successfully updated." }
        format.json { render :show, status: :ok, location: @jugador }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @jugador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jugadors/1 or /jugadors/1.json
  def destroy
    @jugador.destroy

    respond_to do |format|
      format.html { redirect_to jugadors_url, notice: "Jugador was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jugador
      @jugador = Jugador.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def jugador_params
      params.fetch(:jugador, {}).permit(:id, :name, :last_name1, :mail,:posicion, :categoria, :fecha , :telephone, :avatar, :fullname, :name2, :last_name2, :rut, :genero)
    end
end

app/helpers/anuncios_helper.rb
module AnunciosHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/enames_helper.rb
module EnamesHelper
end

app/helpers/jugadors_helper.rb
module JugadorsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/noticia_helper.rb
module NoticiaHelper
end

app/helpers/o2s_helper.rb
module O2sHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jugadors/_form.html.erb
<style>
  #conteiner_3{
    margin-left: 0px;
    margin-right: 0px;
    margin-top: 3%;
    margin-bottom: 2%;
    width : auto;
  }
  #form1{
    width : 100% ;
  }
  #formspace{
    margin-left: 10%;
    margin-right: 10%;
  }
  #datos{
    margin-bottom: 2%;
  }
  select{
    width: 100%;
    padding: 6px 12px;
    border: none;
    border-radius: 4px;
    background-color: #fff; 
  }
  #botones{
    margin-top: 2%;
  }

</style>
<div class="row ml-0" id="conteiner_3">
  <div class="col" id=formspace>
    <%= form_with model: jugador, local: true do |form| %>
      <%= errors_for jugador %>
      <h2 id="datos">Datos Personales</h2>
      <div class="mb-3" id="form1">
        <%= form.label 'Foto' %>
        <%= form.file_field :avatar, class: "form-control-file"  %>
      </div> 
      <div class="row g-3">
        <div class="col-md-6">
          <div class="mb-3" id="form1">
            <%= form.label 'Primer Nombre *', class: "form-label" %>
            <%= form.text_field :name, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="mb-3" id="form1">
            <%= form.label 'Segundo Nombre *', class: "form-label" %>
            <%= form.text_field :name2, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="mb-3" id="form1">
            <%= form.label 'Apellido Paterno *', class: "form-label" %>
            <%= form.text_field :last_name1, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="mb-3" id="form1">
            <%= form.label 'Apellido Materno *', class: "form-label" %>
            <%= form.text_field :last_name2, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="mb-3" id="form1">
          <%= form.label "Correo *", class: "form-label" %>
          <%= form.text_field :mail, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="mb-3" id="form1">
            <%= form.label 'RUT *', class: "form-label" %>
            <%= form.text_field :rut, class: "form-control" , placeholder:"Con puntos y guion" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="mb-3" id="form1">
            <%= form.label "Fecha de Naciemiento *", class: "form-label" %>
            <%= form.date_field :fecha , class: "form-control" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="mb-3" id="form1">
            <%= form.label "Teléfono *", class: "form-label" %>
            <%= form.text_field :telephone, class: "form-control", placeholder:"+569..." %>
          </div>
        </div>
        <div class="col-6">
          <div class="mb-3" id="form1">
            <%= form.label "Género", class: "form-label" %>
            <%= form.select :genero, ["Seleccione una opción","Masculino","Femenino"], class: "form-control1" %>
          </div>
        </div>
        <h2 id="datos">Informacion del Jugador</h2>
        <div class="col-6">
          <div class="mb-3" id="form1">
            <%= form.label "Categoría", class: "form-label" %>
            <%= form.select :categoria, ["Todo Competidor", "Senior", "Sub 19", "Sub 17", "Sub 15", "Sub 13", "Escuelita"], class: "form-control", placeholder:"+569..." %>
          </div>
        </div>
        <div class="col-6">
          <div class="mb-3" id="form1">
            <%= form.label "Posición", class: "form-label" %>
            <%= form.select :posicion, ["Polivalente","Central", "Punta", "Opuesto", "Armador", "Libero"], class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="form-group mt-2 text-center" id="botones">
        <%= form.submit 'Guardar Jugador', class: 'btn btn-primary' %>
        <%= link_to "Volver", :back, class: ["btn", "btn-secondary"] %>
      </div>
    <% end %>
  </div>
</div>

app/views/jugadors/_jugador.html.erb
<div id="<%= dom_id jugador %>">
</div>

app/views/jugadors/_jugador_sort_controls.erb
<div class="btn-group" role="group" aria-label="Sort Jugador">
  <%= link_to 'Todo Competidor', jugadors_path(view: "Todo Competidor"), class:"btn btn-primary"%>
  <%= link_to 'Senior', jugadors_path(view: "Senior"), class:"btn btn-primary"%>
  <%= link_to 'Sub 19', jugadors_path(view: "Sub 19"), class:"btn btn-primary"%>
  <%= link_to 'Sub 17', jugadors_path(view: "Sub 17"), class:"btn btn-primary"%>
  <%= link_to 'Sub 15', jugadors_path(view: "Sub 15"), class:"btn btn-primary"%>
  <%= link_to 'Sub 13', jugadors_path(view: "Sub 13"), class:"btn btn-primary"%>
  <%= link_to 'Escuelita', jugadors_path(view: "Escuelita"), class:"btn btn-primary"%>
</div>

app/views/jugadors/_jugador_tile.html.erb
<div data-jugador-name="<%= jugador.name %>" data-jugador-last_name1="<%= jugador.last_name1 %>">
    <tr data-link="<%= jugador_path(jugador) %>">
        <td><%= image_tag(jugador.avatar.attached? ? jugador.avatar : "profile.png", id:"avatares") %></td>
        <td style="vertical-align: middle;"><a id="tablaa" href="<%= jugador_url(jugador)%>"><%=jugador.name%> <%=jugador.last_name1 %></a></td>
        <td style="vertical-align: middle;"><%=jugador.posicion %></td>
        <td style="vertical-align: middle;"><%=jugador.categoria %></td>
        <%if jugador.deuda == true %>
        <td style="vertical-align: middle; "><a href="<%= jugador_url(jugador)%>" class="badge badge-pill badge-danger" id="lel">Deudor</a></td>
        <%else%>
        <td style="vertical-align: middle; "><a href="<%= jugador_url(jugador)%>" class="badge badge-pill badge-danger" id="lel2">Al Día</a></td>
        <%end%>
    </tr>
</div>

app/views/jugadors/edit.html.erb
<h1 id='titulo'>Edicion de Jugador</h1>
<style>
  #titulo{
    margin-left: 10%;
    margin-top: 3%;

  }
</style>
<%= render "form", jugador: @jugador %>

<br>

<div>
  <%= link_to "Show this jugador", @jugador %> |
  <%= link_to "Back to jugadors", jugadors_path %>
</div>

app/views/jugadors/index.html.erb
<p style="color: green"><%= notice %></p>
<title>Jugadores</title>
<style>
        h1{
          margin-top: 2%;
          margin-left: 8%;
        }

        #newboton{
          margin-left: 2rem ;
          width : 10em;
        }
        #conteiner_row{
          margin-left: 10%;
          margin-right: 0px;
          margin-top: 2%;
          margin-bottom: 2%;
        }
        #lista{
          width : auto;
          margin-left: 10%;
          margin-right: 10%;
          background-color: #d4d3d4;
          background-opacity: 0.8;
        }
        #avatares{
          border-radius: 50%;
          width: 45px;
          height: 45px;
        }
        #tablaa{
          color: #212529;
        }
        #tablaa:hover{
          text-decoration: underline;
        }
        #tj{
          width:100%;
          border: 1px solid;
          border-color: grey;
          border-collapse:collapse;
          border-radius:6px;
          box-shadow: 0 0 0 1px #666;
          background-color: #fff;
        }
        #lel{
          text-align: center;
          width: 60%;
          background-color: red;
        }
        #lel:hover,#lel2:hover{
          text-decoration: none;
          color: white;
          opacity: 0.8;
        }
        #lel2{
          text-align: center;
          width: 60%;
          background-color: green;

        }
      </style>
<div id="jugadores">
  <h1>Jugadores</h1>
  <div class="row" id="conteiner_row">
    <div class="col-md-auto">
    <a class="btn btn-primary" id="newboton" href= <%= new_jugador_path %> role="button">Nuevo Jugador</a>
    </div>
    <div class="col">
      <%= render partial: 'jugadors/jugador_sort_controls' %>
    </div>
  </div>
  <div class="card-header pb-0" id="lista">
    <div class="card-body">
      <table class="table table-striped" style="width:100%" id="tj">
        <thead>
          <tr>
            <th></th>
            <th>Nombre</th>
            <th>Posición</th>
            <th>Categoría</th>
            <th>Pagos</th>
          </tr>
        </thead>
        <tbody>
          <% @jugadors.each do |jugador| %>
            <tr data-link="<%= jugador_path(jugador) %>">
                <td><%= image_tag(jugador.avatar.attached? ? jugador.avatar : "profile.png", id:"avatares") %></td>
                <td style="vertical-align: middle;"><a id="tablaa" href="<%= jugador_url(jugador)%>"><%=jugador.name%> <%=jugador.last_name1 %></a></td>
                <td style="vertical-align: middle;"><%=jugador.posicion %></td>
                <td style="vertical-align: middle;"><%=jugador.categoria %></td>
                <%if jugador.deuda == true %>
                  <td style="vertical-align: middle; "><a href="<%= jugador_url(jugador)%>" class="badge badge-pill badge-danger" id="lel">Deudor</a></td>
                <%else%>
                  <td style="vertical-align: middle; "><a href="<%= jugador_url(jugador)%>" class="badge badge-pill badge-danger" id="lel2">Al Día</a></td>
                <%end%>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>



			

app/views/jugadors/index_cat.html.erb
<p style="color: green"><%= notice %></p>
<title>Jugadores</title>
<style>
        h1{
          margin-top: 2%;
          margin-left: 8%;
        }

        #newboton{
          margin-left: 2rem ;
          width : 10em;
        }
        #conteiner_row{
          margin-left: 10%;
          margin-right: 0px;
          margin-top: 2%;
          margin-bottom: 2%;
        }
        #lista{
          width : auto;
          margin-left: 10%;
          margin-right: 10%;
          background-color: #d4d3d4;
          background-opacity: 0.8;
        }
        #avatares{
          border-radius: 50%;
          width: 45px;
          height: 45px;
        }
        #tablaa{
          color: #212529;
        }
        #tablaa:hover{
          text-decoration: underline;
        }
        #tj{
          width:100%;
          border: 1px solid;
          border-color: grey;
          border-collapse:collapse;
          border-radius:6px;
          box-shadow: 0 0 0 1px #666;
          background-color: #fff;
        }
        #lel{
          text-align: center;
          width: 60%;
          background-color: red;
        }
        #lel:hover,#lel2:hover{
          text-decoration: none;
          color: white;
          opacity: 0.8;
        }
        #lel2{
          text-align: center;
          width: 60%;
          background-color: green;

        }
      </style>
<div id="jugadores">
  <h1>Jugadores</h1>
  <div class="row" id="conteiner_row">
    <div class="col-auto">
    <a class="btn btn-primary" id="newboton" href= <%= new_jugador_path %> role="button">Nuevo Jugador</a>
    </div>
    <div class="col-auto">
      <%= render partial: 'jugadors/jugador_sort_controls' %>
    </div>
    <div class="col-auto">
      <form class="d-flex" style="margin-right: 1em" role="search">
        <input class="form-control me-2" id="search_box" type="search" placeholder="Nombre o Apellido" aria-label="Search">
        <button class="btn btn-outline-primary" id="search_button" type="submit">Buscar</button>
      </form>
    </div>
  </div>
  <div class="card-header pb-0" id="lista">
    <div class="card-body">
      <table class="table table-striped" style="width:100%" id="tj">
        <thead>
          <tr>
            <th></th>
            <th>Nombre</th>
            <th>Posición</th>
            <th>Categoría</th>
            <th>Pagos</th>
          </tr>
        </thead>
        <tbody>
          <div class="row jugadors-list">
            <% @jugadors.each do |jugador| %>
              <%= render partial: 'jugadors/jugador_tile', locals: { jugador: jugador } %>
            <% end %>
          </div>
        </tbody>
      </table>
    </div>
    <style>
      ul{
        list-style-type:none;
        display:flex;
        justify-content: center;
      }
    </style>
    <div class="row justify-content-center">
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  </div>
</div>



			

app/views/jugadors/new.html.erb
<h1 id='titulo'>New jugador</h1>
<style>
  #titulo{
    margin-left: 10%;
    margin-top: 3%;

  }
</style>
<%= render "form", jugador: @jugador %>

app/views/jugadors/search.html.erb
<p style="color: green"><%= notice %></p>
<title>Jugadores</title>
<style>
        h1, h3{
          margin-top: 2%;
          margin-left: 8%;
        }

        #newboton{
          margin-left: 2rem ;
          width : 10em;
        }
        #conteiner_row{
          margin-left: 10%;
          margin-right: 10%;
          margin-top: 2%;
          margin-bottom: 2%;
        }
        #lista{
          width : auto;
          margin-left: 10%;
          margin-right: 10%;
          background-color: #d4d3d4;
          background-opacity: 0.8;
        }
        #avatares{
          border-radius: 50%;
          width: 45px;
          height: 45px;
        }
        #tablaa{
          color: #212529;
        }
        #tablaa:hover{
          text-decoration: underline;
        }
        #tj{
          width:100%;
          border: 1px solid;
          border-color: grey;
          border-collapse:collapse;
          border-radius:6px;
          box-shadow: 0 0 0 1px #666;
          background-color: #fff;
        }
        #lel{
          text-align: center;
          width: 60%;
          background-color: red;
        }
        #lel:hover,#lel2:hover{
          text-decoration: none;
          color: white;
          opacity: 0.8;
        }
        #lel2{
          text-align: center;
          width: 60%;
          background-color: green;

        }
      </style>
<div id="jugadores">
  <h1>Jugadores</h1>
  <div class="row" id="conteiner_row">
    <div class="col-3" style="margin-top:1%;">
      <a class="btn btn-primary" id="newboton" href= <%= new_jugador_path %> role="button">Nuevo Jugador</a>
    </div>
    <div class="col" style="margin-top:1%;">
      <%= render partial: 'jugadors/jugador_sort_controls' %>
    </div>
    <div class="col-auto" style="margin-top:1%;">
        <%= form_tag(busqueda_path, :method => "get") do %>
          <div class="row">
            <div class="col-auto">
              <%= search_field_tag :search, params[:search], placeholder: "Jugador", class:"form-control me-2" %>
            </div>
            <div class="col-auto">
              <%= button_tag  "Buscar", :class => "btn btn-outline-primary", :name => nil %>
            </div>
          </div>
        <%end%>

    </div>
  </div>
  <h3>Resultados de la Busqueda</h3>
  <div class="card-header pb-0" id="lista">
    <div class="card-body">
      <table class="table table-striped" style="width:100%" id="tj">
        <thead>
          <tr>
            <th></th>
            <th>Nombre</th>
            <th>Posición</th>
            <th>Categoría</th>
            <th>Pagos</th>
          </tr>
        </thead>
        <tbody>
          <div class="row jugadors-list">
            <% @jugadors.each do |jugador| %>
              <%= render partial: 'jugadors/jugador_tile', locals: { jugador: jugador } %>
            <% end %>
          </div>
        </tbody>
      </table>
    </div>
  </div>
</div>



			

app/views/jugadors/show.html.erb
<title><%=@jugador.name[0]+". "+@jugador.last_name1%></title>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

<section id="about-section" class="pt-5 pb-5">
    <div class="container wrapabout">
        <div class="red"></div>
        <div class="row" id="centerr">
            <div class="col-lg-6 align-items-center justify-content-left d-flex mb-5 mb-lg-0">
                <div class="blockabout" id="xdd">
                    <div class="blockabout-inner text-center text-sm-start"id="xdd">
                        <div class="title-big pb-3 mb-3">
                            <h3><%=@jugador.name%> <%=@jugador.last_name1%></h3>
                            <h4 class="description-p text-muted pe-0 pe-lg-0">
                            <%= @jugador.posicion%>
                            </h4>
                            <h5 class="description-p text-muted pe-0 pe-lg-0">
                            <%= @jugador.categoria%>
                            </h5>
                        </div>
                        <p class="description-p text-muted pe-0 pe-lg-0">Lorem ipsum dolor sit amet consectetur \n adipisicing elit. Natus quas optio reiciendis deleniti voluptatem facere.</p>
                        <p class="description-p text-muted pe-0 pe-lg-0">Lorem ipsum dolor sit amet consectetur \n adipisicing elit. Natus quas optio reiciendis deleniti voluptatem facere.</p>
                        <p class="description-p text-muted pe-0 pe-lg-0">Lorem ipsum dolor sit amet consectetur \n adipisicing elit. Natus quas optio reiciendis deleniti voluptatem facere.</p>
                        <div class="sosmed-horizontal pt-3 pb-3">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mt-5 mt-lg-0">
                <figure class="potoaboutwrap">
                    <%= image_tag(@jugador.avatar.attached? ? @jugador.avatar : "profile.png", id:"avatares") %>
                </figure>
            </div>
        </div>
    </div>
</section>
<div class="container mt-5 text-center" style="margin-bottom: 3%;">
  <div>
    <%= link_to "Editar Datos", edit_jugador_path(@jugador) , class: ["btn", "btn-primary"] %> 
    <%= link_to "Volver a jugadores", jugadors_path , class: ["btn", "btn-secondary"] %>
    <%= button_to "Eliminar jugador", @jugador, method: :delete , class: 'btn btn-danger', id:'botone' %>
  </div>
</div>
<style>
  #botone{
    margin-top: 1%;
  }
  #centerr{
    margin-left: 10%;
  }
  #avatares{
    width: 60%;
    height: auto;
    border-radius: 25px;
  }
  #xdd{
    border-radius: 25px;
  }
  #about-section {
    position: relative;
  }

  .blockabout {
      padding: 20px;
      background: white;
  }

  .blockabout-inner {
      padding: 30px;
      border: 1px solid rgba(32, 33, 36, 0.1);
  }

  .sosmed-horizontal a i {
      border: 1px solid #070707;
      border-radius: 50%;
      color: #070707;
      display: inline-block;
      height: 30px;
      width: 30px;
      line-height: 30px;
      margin: auto 3px;
      font-size: 15px;
      text-align: center;
      transition: all 0.3s;
  }

  .rey-btn {
      border: 2px solid #070707;
      padding: 10px 40px;
      text-transform: uppercase;
      letter-spacing: 2px;
      font-size: 13px;
      font-weight: 700;
      border-radius: 50px;
      transition: all 0.3s;
  }
</style>