config/routes.rb
Rails.application.routes.draw do
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
  resources :o2s
  resources :enames
  resources :evaluacions
  resources :anuncios
  resources :horarios
  resources :consultations
  resources :noticia
  resources :jugadors
  resources :entrenadors
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get '/evaluaciones', to: 'evaluacions#main_index'
  get '/busqueda', to: "jugadors#search"
end

app/models/anuncio.rb
class Anuncio < ApplicationRecord
end

app/models/consultation.rb
class Consultation < ApplicationRecord
    validates_presence_of :start_time, :title, :description
end

app/models/ename.rb
class Ename < ApplicationRecord
    has_many :evaluacions, dependent: :destroy
    has_many :evaluacion_tecs, dependent: :destroy
end

app/models/entrenador.rb
class Entrenador < ApplicationRecord
    has_one_attached :avatar
end

app/models/evaluacion.rb
class Evaluacion < ApplicationRecord
    before_save :set_defaults
    belongs_to :ename , optional: true
    belongs_to :jugador
    validates_presence_of :ename_id
    
    private
    def set_defaults
        self.altura ||= 0
        self.embergadura ||= 0
        self.peso ||= 0
        self.max_pres ||= 0
        self.max_squat ||= 0
        self.max_dl ||= 0
        self.max_jump_incompleto ||= 0
        self.max_jump_completo ||= 0
        self.max_jump_libre ||= 0
        self.max_jump_carrera ||= 0
        self.max_v1 ||= 0
        self.max_v2 ||= 0
        self.max_time ||= "00:00"
    end

end

app/models/evaluacion_tec.rb
class EvaluacionTec < ApplicationRecord
    belongs_to :jugador
end

app/models/horario.rb
class Horario < ApplicationRecord
end

app/models/jugador.rb
class Jugador < ApplicationRecord
    has_one_attached :avatar
    has_many :evaluacions, dependent: :destroy
    has_many :evaluacion_tecs, dependent: :destroy
    validates_presence_of :fecha, :name, :last_name1, :rut, :categoria
end

app/models/noticium.rb
class Noticium < ApplicationRecord
    has_many_attached : photos
end

app/models/o2.rb
class O2 < ApplicationRecord
    validates_presence_of :fecha ,:title, :categoria, :torneo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar

  #this gives you custom message for the error
  validates :email, :uniqueness => { :message => "El correo ya esta registrado." }
  
  #an even better way
  def email=(email)
    super(email.downcase.strip)
  end
end

app/controllers/anuncios_controller.rb
class AnunciosController < ApplicationController
  before_action :set_anuncio, only: %i[ show edit update destroy ]

  # GET /anuncios or /anuncios.json
  def index
    @anuncios = Anuncio.all
  end

  # GET /anuncios/1 or /anuncios/1.json
  def show
  end

  # GET /anuncios/new
  def new
    @anuncio = Anuncio.new
  end

  # GET /anuncios/1/edit
  def edit
  end

  # POST /anuncios or /anuncios.json
  def create
    @anuncio = Anuncio.new(anuncio_params)

    respond_to do |format|
      if @anuncio.save
        format.html { redirect_to anuncio_url(@anuncio), notice: "Anuncio was successfully created." }
        format.json { render :show, status: :created, location: @anuncio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @anuncio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anuncios/1 or /anuncios/1.json
  def update
    respond_to do |format|
      if @anuncio.update(anuncio_params)
        format.html { redirect_to anuncio_url(@anuncio), notice: "Anuncio was successfully updated." }
        format.json { render :show, status: :ok, location: @anuncio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @anuncio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anuncios/1 or /anuncios/1.json
  def destroy
    @anuncio.destroy

    respond_to do |format|
      format.html { redirect_to anuncios_url, notice: "Anuncio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anuncio
      @anuncio = Anuncio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def anuncio_params
      params.require(:anuncio).permit(:title, :description, :categoria, :remitente)
    end
end

app/helpers/anuncios_helper.rb
module AnunciosHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/enames_helper.rb
module EnamesHelper
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/noticia_helper.rb
module NoticiaHelper
end

app/helpers/o2s_helper.rb
module O2sHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/anuncios/_anuncio.html.erb
<div id="<%= dom_id anuncio %>">
  <p>
    <strong>Title:</strong>
    <%= anuncio.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= anuncio.description %>
  </p>

  <p>
    <strong>Categoria:</strong>
    <%= anuncio.categoria %>
  </p>

  <p>
    <strong>Remitente:</strong>
    <%= anuncio.remitente %>
  </p>

</div>

app/views/anuncios/_form.html.erb
<style>
  #conteiner_3{
    margin-left: 0px;
    margin-right: 0px;
    margin-top: 3%;
    margin-bottom: 2%;
    width : auto;
  }
  #form1{
    width : 100% ;
  }
  #formspace{
    margin-left: 10%;
    margin-right: 10%;
  }
  select{
    width: 100%;
    padding: 6px 12px;
    border: none;
    border-radius: 4px;
    background-color: #fff; 
  }
  textarea{
    height: 19em;
  }

</style>
<div class="row ml-0" id="conteiner_3">
  <div class="col" id=formspace>
    <%= form_with model: anuncio, local: true do |form| %>
      <%= errors_for anuncio %> 
      <div class="row g-3">
        <div class="col-md-9">
          <div class="mb-3" id="form1">
            <%= form.label 'Nombre', class: "form-label" %>
            <%= form.text_field :title , class: "form-control" %>
          </div>
        </div>
        <div class="col-3">
          <div class="mb-3" id="form1">
            <%= form.label "Categoria", class: "form-label" %>
            <%= form.select :categoria, ["Todas","Todo Competidor", "Senior", "Sub 20", "Sub 19", "Sub 18", "Sub 17", "Sub 16", "Sub 15", "Sub 14", "Sub 13", "Sub 12", "Escuelita"], class: "form-control" %>
          </div>
        </div>
        <div class="col-md-12">
          <div class="mb-3" id="form1">
            <%= form.label 'Mensaje', class: "form-label" %>
            <%= form.text_area :description , class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="form-group mt-2">
        <%= form.submit 'Enviar Anuncio', class: 'btn btn-primary' %>
        <%= link_to "Volver", :back, class: ["btn", "btn-secondary"] %>
      </div>
    <% end %>
  </div>
</div>

app/views/anuncios/edit.html.erb
<h1>Editing anuncio</h1>

<%= render "form", anuncio: @anuncio %>

<br>

<div>
  <%= link_to "Show this anuncio", @anuncio %> |
  <%= link_to "Back to anuncios", anuncios_path %>
</div>

app/views/anuncios/index.html.erb
<div class="container mt-5 text-center">
  <title>Anuncios</title>
  <h1>Anuncios</h1>
</div>
<style>
  #row1{
    margin-left: 10%;
    margin-right: 10%;
    width: 80%;
    border: 1px solid black;
    border-radius: 4px;
    
  }
  #butoncito{
    margin-top: 2%;
    margin-bottom: 3%;
    width: 30%;
    margin-left: 35%;
    margin-right: 35%;
    align: center;
  }
  #deletebtn{
    text-align: right;
  }
  .card {
    box-shadow: 0 2px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
  }

  .card {
    margin-left: auto;
    margin-right: auto;
    width: 60%;
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
  }

  .card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
  }
  #foto.col{
    width: min-content;
  }
  #xd{
    margin-top: 1%;

  }
  .media-body{
    margin-top: 1%;
  }
  #lineas{
    white-space: pre-line
  }
</style>
<%= link_to "Nuevo Anuncio", new_anuncio_path, class: ["btn", "btn-primary"], id:"butoncito" %>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css" integrity="sha256-46r060N2LrChLLb5zowXQ72/iKKNiw/lAmygmHExk/o=" crossorigin="anonymous" />
<div class="container">
<div class="main-body p-0">
        <!-- Inner main body -->
        <% @anuncios.reverse_each do |anuncio| %>
        <!-- Forum List -->

            <div class="card mb-2">
                <div class="card-body p-2 p-sm-3">
                    <div class="media forum-item">
                        <div class="row" >
                            <div class="col-md-auto" id="foto">
                            <a href="#" data-toggle="collapse" data-target=".forum-content"><img src="https://bootdey.com/img/Content/avatar/avatar1.png" class="mr-3 rounded-circle" width="50" alt="User" /></a>
                            </div>
                            <div class="col-md-auto" id="xd" >
                                <h6 ><a href="#" data-toggle="collapse" data-target=".forum-content" class="text-body"><%= anuncio.title%></a></h6>
                                <p class="text-secondary" id="lineas">
                                <%= anuncio.description%>
                            </p>
                            </div>
                        </div>
                        <div class="media-body">
                            <p class="text-muted"><%=anuncio.remitente%> <span class="text-secondary font-weight-bold"> <%= time_ago_in_words(anuncio.created_at) %></span></p>
                        </div>
                    </div>

                </div>
            </div>

        <!-- /Forum List -->
        <%end%>
</div>

app/views/anuncios/new.html.erb
<title>Nuevo Anuncio</title>
<div class="container mt-5 text-left">
  <h1 class="text-center">Nuevo Anuncio</h1>

  <%= render "form", anuncio: @anuncio %>

  <br>

</div>

app/views/anuncios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @anuncio %>

<div>
  <%= link_to "Edit this anuncio", edit_anuncio_path(@anuncio) %> |
  <%= link_to "Back to anuncios", anuncios_path %>

  <%= button_to "Destroy this anuncio", @anuncio, method: :delete %>
</div>